version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "testDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgresData:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresData: